const app = document.querySelector('#app');
const storageKey = 'vibora-state-v1';
const defaultState = { profile: null, room: null, messages: [{ name: 'Aman', text: 'This looks perfect for tonight!' }], playing: false, vote: null };
let state = JSON.parse(localStorage.getItem(storageKey) || 'null') || defaultState;
const persist = () => localStorage.setItem(storageKey, JSON.stringify(state));
const esc = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function shell(content) { return `<div class="shell"><nav class="nav"><button class="brand ghost" data-action="home"><span class="brand-mark">V</span>Vibora</button><div class="nav-actions">${state.profile ? `<span class="hint">Hi, ${esc(state.profile.name.split(' ')[0])}</span><span class="avatar">${esc(state.profile.name.slice(0,2).toUpperCase())}</span>` : ''}</div></nav>${content}</div>`; }
function toast(message) { const el = document.querySelector('#toast-template').content.firstElementChild.cloneNode(true); el.textContent = message; document.body.append(el); setTimeout(() => el.remove(), 2600); }
function landing() { app.innerHTML = shell(`<section class="hero"><div class="eyebrow">Your entertainment, more social</div><h1>Never spend 40 minutes deciding <span class="gradient">what to watch.</span></h1><p class="lead">Vibora helps your group find something everyone will enjoy, then brings you together in one room.</p><div class="actions"><button class="btn primary" data-action="start">Get started free</button><button class="btn secondary" data-action="demo">Explore the demo room</button></div><div class="stats"><span><b>2 min</b>to pick a title</span><span><b>1 room</b>for the whole group</span><span><b>0</b>OTT credentials stored</span></div></section>`); }
function auth() { app.innerHTML = shell(`<section class="card auth"><div class="eyebrow">Welcome to Vibora</div><h1>Let’s make movie night easier.</h1><p class="hint">Create your profile. No streaming-service passwords are ever needed.</p><label class="field">YOUR NAME<input id="name" placeholder="e.g. Gurpreet Singh" autocomplete="name"></label><button class="btn primary wide" data-action="continue-auth">Continue</button><div class="divider">or</div><button class="btn secondary wide" data-action="demo-profile">Use demo profile</button></section>`); }
const interests = ['Action','Comedy','Thriller','Romance','Horror','Sci-fi','Anime','Cricket','Bollywood','K-dramas','Punjabi music','Documentary'];
function onboarding() { const selected = state.draftInterests || []; app.innerHTML = shell(`<section class="card setup"><div class="eyebrow">Step 1 of 1</div><h1>What brings you back to the screen?</h1><p class="hint">Choose at least 3 interests. Your group recommendations will improve as you use Vibora.</p><div class="chips">${interests.map(x => `<button class="chip ${selected.includes(x) ? 'selected':''}" data-interest="${x}">${x}</button>`).join('')}</div><button class="btn primary" data-action="finish-onboarding">Create my Vibora</button></section>`); }
function home() { app.innerHTML = shell(`<section class="home-top"><div><div class="eyebrow">Tonight on Vibora</div><h1>What are you in the mood for?</h1></div><button class="btn secondary" data-action="edit-profile">Edit interests</button></section><section class="grid"><button class="card action-card" data-action="create-room"><span class="icon">✦</span><h2>Watch with friends</h2><p>Create a private room and share an invite code.</p></button><button class="card action-card" data-action="join-room"><span class="icon">↗</span><h2>Join a room</h2><p>Enter a code from a friend and pick together.</p></button><button class="card action-card" data-action="demo"><span class="icon">✺</span><h2>Ask group AI</h2><p>See how Vibora finds the right compromise.</p></button></section>`); }
function room() { const r = state.room || { name:'Friday Film Club', code:'VIBORA7' }; const members = [state.profile.name, 'Aman', 'Priya']; const recs = [{title:'Knives Out',meta:'91% group match · 2h 10m · Mystery comedy'},{title:'The Nice Guys',meta:'87% group match · 1h 56m · Buddy comedy'},{title:'Andhadhun',meta:'84% group match · 2h 19m · Hindi thriller'}]; app.innerHTML = shell(`<section class="room-head"><div><div class="eyebrow">Private watch room</div><h1>${esc(r.name)}</h1><p>Choose together. Playback uses an authorized provider player.</p></div><button class="code" data-action="copy-code">Invite: ${r.code} ⧉</button></section><section class="room-layout"><div><article class="card player"><div class="player-content"><div class="play-circle">${state.playing?'❚❚':'▶'}</div><h2>${state.playing ? 'Knives Out is playing' : 'Ready when your group is'}</h2><p>${state.playing ? '00:24 · simulated synchronized playback' : 'Vote on a recommendation to start'}</p></div></article><div class="controls"><div class="control-group"><button class="icon-btn" data-action="toggle-play">${state.playing?'❚❚ Pause':'▶ Play'}</button><button class="icon-btn" data-action="seek">↺ 10</button><span class="time">00:24 / 2:10:00</span></div><button class="btn secondary" data-action="recommend">✦ Ask group AI</button></div></div><aside class="side"><article class="card"><h3>In the room · ${members.length}</h3>${members.map((m,i)=>`<div class="member"><span class="avatar">${esc(m.slice(0,2).toUpperCase())}</span><span>${esc(m)}<small>${i===0?'You':'Watching'}</small></span><i class="presence"></i></div>`).join('')}</article><article class="card"><h3>Best for this group</h3>${recs.map((x,i)=>`<button class="recommendation ghost" data-vote="${i}"><b>${state.vote===i?'✓ ':''}${x.title}</b><span>${x.meta}</span></button>`).join('')}</article><article class="card chat"><h3>Room chat</h3><div class="messages">${state.messages.map(m=>`<div class="message"><b>${esc(m.name)}</b>${esc(m.text)}</div>`).join('')}</div><form class="chat-form" id="chat-form"><input id="chat-input" maxlength="140" placeholder="Say something…"><button class="btn primary">Send</button></form></article></aside></section>`); }
function modal(type) { const join = type === 'join'; document.body.insertAdjacentHTML('beforeend', `<div class="modal-backdrop"><section class="card modal"><div class="eyebrow">${join?'Join a room':'Create a room'}</div><h2>${join?'Your friends are waiting.':'Bring your people together.'}</h2><p>${join?'Enter the invite code your host shared.':'Start private. Invite friends with a simple code.'}</p><label class="field">${join?'INVITE CODE':'ROOM NAME'}<input id="modal-input" placeholder="${join?'e.g. VIBORA7':'e.g. Friday Film Club'}"></label><button class="btn primary wide" data-modal-action="${join?'join':'create'}">${join?'Join room':'Create room'}</button><button class="btn ghost wide" data-modal-action="close">Cancel</button></section></div>`); }
function render() { if (!state.profile) return landing(); if (!state.profile.interests) return onboarding(); if (state.room) return room(); return home(); }
document.addEventListener('click', e => { const action = e.target.closest('[data-action]')?.dataset.action; const interest = e.target.closest('[data-interest]')?.dataset.interest; const vote = e.target.closest('[data-vote]')?.dataset.vote; if (interest) { state.draftInterests ||= []; state.draftInterests = state.draftInterests.includes(interest) ? state.draftInterests.filter(x=>x!==interest) : [...state.draftInterests,interest]; return onboarding(); } if (vote !== undefined) { state.vote=Number(vote); state.playing=true; persist(); toast('Vote recorded — Knives Out is now playing for everyone.'); return room(); } if (!action) return; if (action==='start') return auth(); if (action==='home') { state.room=null;persist();return render(); } if (action==='demo') { state.profile ||= {name:'Gurpreet',interests:['Comedy','Thriller','Bollywood']}; state.room={name:'Friday Film Club',code:'VIBORA7'};persist();return room(); } if (action==='continue-auth') { const name=document.querySelector('#name').value.trim(); if (!name) return toast('Add your name to continue.'); state.profile={name};persist();return onboarding(); } if (action==='demo-profile') { state.profile={name:'Gurpreet',interests:null};persist();return onboarding(); } if (action==='finish-onboarding') { if ((state.draftInterests||[]).length<3) return toast('Choose at least three interests.'); state.profile.interests=state.draftInterests; delete state.draftInterests;persist();return home(); } if (action==='edit-profile') { state.draftInterests=state.profile.interests;return onboarding(); } if (action==='create-room') return modal('create'); if (action==='join-room') return modal('join'); if (action==='copy-code') return navigator.clipboard?.writeText(state.room.code).then(()=>toast('Invite code copied.')).catch(()=>toast(`Invite code: ${state.room.code}`)); if (action==='toggle-play') { state.playing=!state.playing;persist();return room(); } if (action==='seek') return toast('Rewound 10 seconds for the room.'); if (action==='recommend') return toast('Group AI: Knives Out is the best compromise tonight.'); });
document.addEventListener('click', e => { const action=e.target.closest('[data-modal-action]')?.dataset.modalAction; if (!action) return; if(action==='close') return document.querySelector('.modal-backdrop').remove(); const input=document.querySelector('#modal-input').value.trim(); if(!input) return toast('Please enter a value.'); state.room={name:action==='create'?input:'Friday Film Club',code:action==='join'?input.toUpperCase():'VIBORA7'};persist();document.querySelector('.modal-backdrop').remove();room(); });
document.addEventListener('submit', e => { if(e.target.id!=='chat-form') return; e.preventDefault(); const input=document.querySelector('#chat-input'); const text=input.value.trim(); if(!text) return; state.messages.push({name:state.profile.name.split(' ')[0],text});persist();room(); });
render();
